
  # ----- add group ------
    - name: add group
      group:
        name: "{{ group_name_to_add }}"
        state: present

  # ----- delete group ------
    - name: delete group
      group:
        name: "{{ group_name_to_delete }}"
        state: absent 
