- name: Create users with specific password
  user:
    name: "{{ item.name }}"
    state: absent
    groups: group1
    shell: /bin/bash
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
  with_items:
    - { name: "user1", password: "pass1" }
    - { name: "user2", password: "pass2" }
    - { name: "user3", password: "pass3" }



