
# ----- enable ports
    - name: open port "{{ port_to_open }}"
      ufw:
        rule: allow
        port: "{{ port_to_open }}"
        proto: tcp

# ----- disable ports
    - name: close port "{{ port_to_close }}"
      ufw:
        rule: deny
        port: "{{ port_to_close }}"
        proto: tcp
