      - name: git add all new files
        shell: git add -A # shell: git add -A will add all new files to the staging area.
        args: 
          chdir: "/home/ilyas/ansible_project"
        ignore_errors: true 

      - name: git commit
        shell: git commit -a -m "test push" # shell: git commit -m "test push" will commit all changes to the local repository.
        args:
          chdir: "/home/ilyas/ansible_project"
        ignore_errors: true

      - name: git push
        shell: git push --all --force # shell: git push --all --force will push all to the remote repository.
        args:
          chdir: "/home/ilyas/ansible_project"
        ignore_errors: true